CREATE TABLE IF NOT EXISTS formulas (id TEXT PRIMARY KEY, raw_json TEXT);
CREATE TABLE IF NOT EXISTS equipments (
    id TEXT PRIMARY KEY,
    detail_url TEXT,
    image TEXT,
    name TEXT,
    type TEXT,
    description TEXT,
    effect_text TEXT,
    unlock_text TEXT,
    deposit_stats TEXT,
    unlock_stats TEXT,
    jobs TEXT,
    formula_id TEXT,
    raw_html TEXT
);
CREATE TABLE IF NOT EXISTS headwears (
    id TEXT PRIMARY KEY,
    detail_url TEXT,
    image TEXT,
    name TEXT,
    type TEXT,
    description TEXT,
    quality TEXT,
    effect_text TEXT,
    unlock_text TEXT,
    deposit_stats TEXT,
    unlock_stats TEXT,
    jobs TEXT,
    formula_id TEXT,
    raw_html TEXT
);
CREATE TABLE IF NOT EXISTS monsters (
    id TEXT PRIMARY KEY,
    detail_url TEXT,
    image TEXT,
    name TEXT,
    race TEXT,
    element TEXT,
    size TEXT,
    location TEXT,
    level INTEGER,
    hp TEXT,
    base_exp TEXT,
    job_exp TEXT,
    str INTEGER,
    agi INTEGER,
    vit INTEGER,
    int_stat INTEGER,
    dex INTEGER,
    luk INTEGER,
    atk TEXT,
    matk TEXT,
    def TEXT,
    mdef TEXT,
    hit TEXT,
    flee TEXT,
    move_speed TEXT,
    aspd TEXT,
    raw_json TEXT,
    raw_html TEXT
);